services:
  app1:
    build: ./app
    container_name: app1
  app2:
    build: ./app
    container_name: app2
  nginx:
    build: ./nginx
    ports:
      - "8082:80"
    depends_on:
      - app1
      - app2